[0m17:43:22.581783 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C0EC6EF170>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C0EC7D5EE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C0EC7D5D60>]}


============================== 17:43:22.589804 | 4da567d5-9e05-495c-9148-11b234fbc81b ==============================
[0m17:43:22.589804 [info ] [MainThread]: Running with dbt=1.7.4
[0m17:43:22.589804 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\ankit\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt init pizza_etl', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:43:22.590803 [debug] [MainThread]: Starter project path: E:\here\git\dbt_pizza\.vdbt\Lib\site-packages\dbt\include\starter_project
[0m17:43:22.756222 [info ] [MainThread]: 
Your new dbt project "pizza_etl" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m17:43:22.757223 [info ] [MainThread]: Setting up your profile.
[0m17:43:46.913053 [debug] [MainThread]: Command `dbt init` succeeded at 17:43:46.913053 after 24.43 seconds
[0m17:43:46.914054 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C0EC657860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C0EC5E2330>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C0EC7D6C90>]}
[0m17:43:46.914054 [debug] [MainThread]: Flushing usage events
[0m17:55:52.011976 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BC5BFD9A30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BC5BFD9B80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BC5BFD96D0>]}


============================== 17:55:52.015982 | ceda43f6-4f0e-4a98-a952-7181af7ed007 ==============================
[0m17:55:52.015982 [info ] [MainThread]: Running with dbt=1.7.4
[0m17:55:52.015982 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\ankit\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m17:55:52.015982 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path E:\here\git\dbt_pizza\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:55:52.016979 [debug] [MainThread]: Command `dbt run` failed at 17:55:52.016979 after 0.05 seconds
[0m17:55:52.017937 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BC5BEFF0E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BC5BEEF0B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BC5BFD9B80>]}
[0m17:55:52.017937 [debug] [MainThread]: Flushing usage events
[0m22:06:34.868264 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B97B705070>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B97B705A90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B97B7058E0>]}


============================== 22:06:34.872265 | e74b7276-6fac-474f-bda2-badf7f45c2c8 ==============================
[0m22:06:34.872265 [info ] [MainThread]: Running with dbt=1.7.4
[0m22:06:34.873380 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\ankit\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt test', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:06:34.873380 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path E:\here\git\dbt_pizza\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:06:34.874383 [debug] [MainThread]: Command `dbt test` failed at 22:06:34.873380 after 0.06 seconds
[0m22:06:34.874383 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B97B452E70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B97B22D040>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B97B4370E0>]}
[0m22:06:34.874383 [debug] [MainThread]: Flushing usage events
[0m21:23:56.594715 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E09590ABD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E09590A600>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E09590AC00>]}


============================== 21:23:56.608218 | b9b8bee4-7a46-44e3-97b8-eb2a83936f1d ==============================
[0m21:23:56.608218 [info ] [MainThread]: Running with dbt=1.7.4
[0m21:23:56.608218 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\ankit\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m21:23:56.609218 [info ] [MainThread]: dbt version: 1.7.4
[0m21:23:56.609218 [info ] [MainThread]: python version: 3.12.1
[0m21:23:56.609218 [info ] [MainThread]: python path: E:\here\git\dbt_pizza\.vdbt\Scripts\python.exe
[0m21:23:56.609218 [info ] [MainThread]: os info: Windows-11-10.0.22621-SP0
[0m21:23:56.811013 [info ] [MainThread]: Using profiles dir at C:\Users\ankit\.dbt
[0m21:23:56.811013 [info ] [MainThread]: Using profiles.yml file at C:\Users\ankit\.dbt\profiles.yml
[0m21:23:56.812011 [info ] [MainThread]: Using dbt_project.yml file at E:\here\git\dbt_pizza\dbt_project.yml
[0m21:23:56.812011 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m21:23:56.813011 [debug] [MainThread]: Command `dbt debug` failed at 21:23:56.812011 after 0.27 seconds
[0m21:23:56.813011 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E0956528A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E0956E3050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E09516CFE0>]}
[0m21:23:56.813011 [debug] [MainThread]: Flushing usage events
[0m22:08:44.057946 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001703A701B20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001703A701700>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001703A701EE0>]}


============================== 22:08:44.061954 | 8a662b4b-b94f-44bc-93f9-4272d4ec49bd ==============================
[0m22:08:44.061954 [info ] [MainThread]: Running with dbt=1.7.4
[0m22:08:44.062955 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\ankit\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt run --select stg_pizzatypes', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m22:08:44.062955 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path E:\here\git\dbt_pizza\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:08:44.063956 [debug] [MainThread]: Command `dbt run` failed at 22:08:44.063956 after 0.04 seconds
[0m22:08:44.063956 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001703A1059A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017039D8F860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001703A0557C0>]}
[0m22:08:44.063956 [debug] [MainThread]: Flushing usage events
[0m19:17:44.552731 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D69CC010A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D69C8A9160>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D69CC019A0>]}


============================== 19:17:44.563557 | ab352361-a797-4f12-b26b-54b619af1fdb ==============================
[0m19:17:44.563557 [info ] [MainThread]: Running with dbt=1.7.4
[0m19:17:44.563557 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\ankit\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run --select stg_pizzatypes', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:17:44.564561 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path E:\here\git\dbt_pizza\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:17:44.564561 [debug] [MainThread]: Command `dbt run` failed at 19:17:44.564561 after 0.06 seconds
[0m19:17:44.565561 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D69C7514F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D69C2D1F70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D69C65F0E0>]}
[0m19:17:44.565561 [debug] [MainThread]: Flushing usage events
[0m16:52:25.875193 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000209C44D99A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000209C44D9CD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000209C44D96A0>]}


============================== 16:52:25.891525 | d1bd6e7e-364c-4c67-9d8f-c14455e26f2f ==============================
[0m16:52:25.891525 [info ] [MainThread]: Running with dbt=1.7.4
[0m16:52:25.891525 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\ankit\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt test', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m16:52:25.892527 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path E:\here\git\dbt_pizza\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:52:25.892527 [debug] [MainThread]: Command `dbt test` failed at 16:52:25.892527 after 0.05 seconds
[0m16:52:25.893526 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000209C3BD5AF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000209C40E0FB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000209C3F05190>]}
[0m16:52:25.893526 [debug] [MainThread]: Flushing usage events
[0m20:48:56.348716 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BB9E205D90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BB9D9EA060>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BB9E205190>]}


============================== 20:48:56.357716 | 7d3b337d-9b3f-4a98-9290-c13f27fd06da ==============================
[0m20:48:56.357716 [info ] [MainThread]: Running with dbt=1.7.4
[0m20:48:56.358708 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\ankit\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt docs generate', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m20:48:56.358708 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path E:\here\git\dbt_pizza\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:48:56.359708 [debug] [MainThread]: Command `dbt docs generate` failed at 20:48:56.359708 after 0.06 seconds
[0m20:48:56.360707 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BB9D7ACE60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BB9DD8D820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002BB9DFD5F10>]}
[0m20:48:56.360707 [debug] [MainThread]: Flushing usage events
[0m20:49:09.533962 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024F71606A50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024F71606DE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024F71605190>]}


============================== 20:49:09.539954 | 5ec7e6a2-4de7-44bb-8013-6f1e061fe191 ==============================
[0m20:49:09.539954 [info ] [MainThread]: Running with dbt=1.7.4
[0m20:49:09.539954 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\ankit\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt docs serve', 'send_anonymous_usage_stats': 'True'}
[0m20:49:09.539954 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path E:\here\git\dbt_pizza\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:49:09.540962 [debug] [MainThread]: Command `dbt docs serve` failed at 20:49:09.540962 after 0.06 seconds
[0m20:49:09.540962 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024F715D5FD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024F713E14F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024F70F55820>]}
[0m20:49:09.541963 [debug] [MainThread]: Flushing usage events
[0m21:12:29.865976 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020BB1CDA1E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020BB1CD9EB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020BB1CDA2D0>]}


============================== 21:12:29.881994 | 943a62dd-3ce4-4cdb-bd89-a9563c746688 ==============================
[0m21:12:29.881994 [info ] [MainThread]: Running with dbt=1.7.4
[0m21:12:29.882994 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\ankit\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt docs serve', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m21:12:29.882994 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path E:\here\git\dbt_pizza\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:12:29.882994 [debug] [MainThread]: Command `dbt docs serve` failed at 21:12:29.882994 after 0.06 seconds
[0m21:12:29.884304 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020BB18E14F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020BB1CD9EB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020BB1CDA720>]}
[0m21:12:29.884304 [debug] [MainThread]: Flushing usage events
[0m20:54:11.339936 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002465968CE30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000246599FAF00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000246599F9CD0>]}


============================== 20:54:11.350675 | 466368f1-35a1-4378-85f7-dbb8caf9b483 ==============================
[0m20:54:11.350675 [info ] [MainThread]: Running with dbt=1.7.4
[0m20:54:11.351677 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\ankit\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m20:54:11.351677 [info ] [MainThread]: dbt version: 1.7.4
[0m20:54:11.351677 [info ] [MainThread]: python version: 3.12.2
[0m20:54:11.351677 [info ] [MainThread]: python path: E:\here\git\dbt_pizza\.vdbt\Scripts\python.exe
[0m20:54:11.353061 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m20:54:11.562810 [info ] [MainThread]: Using profiles dir at C:\Users\ankit\.dbt
[0m20:54:11.563806 [info ] [MainThread]: Using profiles.yml file at C:\Users\ankit\.dbt\profiles.yml
[0m20:54:11.563806 [info ] [MainThread]: Using dbt_project.yml file at E:\here\git\dbt_pizza\dbt_project.yml
[0m20:54:11.570353 [info ] [MainThread]: adapter type: postgres
[0m20:54:11.570353 [info ] [MainThread]: adapter version: 1.7.4
[0m20:54:11.570353 [info ] [MainThread]: Configuration:
[0m20:54:11.570353 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m20:54:11.571350 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m20:54:11.571350 [info ] [MainThread]: Required dependencies:
[0m20:54:11.571350 [debug] [MainThread]: Executing "git --help"
[0m20:54:11.590857 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--config-env=<name>=<envvar>] <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m20:54:11.591906 [debug] [MainThread]: STDERR: "b''"
[0m20:54:11.591906 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m20:54:11.591906 [info ] [MainThread]: Connection:
[0m20:54:11.592910 [info ] [MainThread]:   host: 192.168.0.17
[0m20:54:11.592910 [info ] [MainThread]:   port: 5432
[0m20:54:11.592910 [info ] [MainThread]:   user: dev_user
[0m20:54:11.593909 [info ] [MainThread]:   database: dev_db
[0m20:54:11.593909 [info ] [MainThread]:   schema: pizza
[0m20:54:11.593909 [info ] [MainThread]:   connect_timeout: 10
[0m20:54:11.594909 [info ] [MainThread]:   role: None
[0m20:54:11.594909 [info ] [MainThread]:   search_path: None
[0m20:54:11.594909 [info ] [MainThread]:   keepalives_idle: 0
[0m20:54:11.595910 [info ] [MainThread]:   sslmode: None
[0m20:54:11.595910 [info ] [MainThread]:   sslcert: None
[0m20:54:11.596910 [info ] [MainThread]:   sslkey: None
[0m20:54:11.596910 [info ] [MainThread]:   sslrootcert: None
[0m20:54:11.596910 [info ] [MainThread]:   application_name: dbt
[0m20:54:11.597910 [info ] [MainThread]:   retries: 1
[0m20:54:11.597910 [info ] [MainThread]: Registered adapter: postgres=1.7.4
[0m20:54:11.597910 [debug] [MainThread]: Acquiring new postgres connection 'debug'
[0m20:54:11.598910 [debug] [MainThread]: Using postgres connection "debug"
[0m20:54:11.598910 [debug] [MainThread]: On debug: select 1 as id
[0m20:54:11.598910 [debug] [MainThread]: Opening a new connection, currently in state init
[0m20:54:11.781885 [debug] [MainThread]: SQL status: SELECT 1 in 0.0 seconds
[0m20:54:11.783889 [debug] [MainThread]: On debug: Close
[0m20:54:11.784885 [info ] [MainThread]:   Connection test: [[32mOK connection ok[0m]

[0m20:54:11.785886 [info ] [MainThread]: [31m1 check failed:[0m
[0m20:54:11.786890 [info ] [MainThread]: Project loading failed for the following reason:
 project path <E:\here\git\dbt_pizza\dbt_project.yml> not found

[0m20:54:11.788885 [debug] [MainThread]: Command `dbt debug` failed at 20:54:11.788885 after 0.50 seconds
[0m20:54:11.788885 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m20:54:11.789883 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000246593E5BE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000246598EEF00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000246599D2A20>]}
[0m20:54:11.789883 [debug] [MainThread]: Flushing usage events
